# Generated by Django 5.2.5 on 2025-09-09 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouletteGameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bet', models.DecimalField(decimal_places=2, max_digits=8)),
                ('winning_number', models.IntegerField()),
                ('winning_color', models.CharField(max_length=10)),
                ('total_payout', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bets_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blackjack.player')),
            ],
        ),
        migrations.CreateModel(
            name='RouletteBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(max_length=20)),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bet_number', models.IntegerField(blank=True, null=True)),
                ('won', models.BooleanField(default=False)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blackjack.roulettegamemodel')),
            ],
        ),
    ]
